### ISSUE TITLE
dotnet publish of the sample solution throws an null reference exception while dotnet run works properly

### ISSUE THREAD

**Issue by piskernik** [OrchardCMS/OrchardCore.Samples#3]
I used the unchanged sample project and tried to publish it to a local folder. Running the project from within Visual Studio worked, ´dotnet run´ worked as well. Only ´dotnet publish -o ...´resulted in a project, where a null reference exception was thrown, when I tried the route to Module1/Home/Index. Am I missing something here or is this a bug? (BTW: This happened on a Mac and on a Windows machine)

      Connection id "0HL8I8AFQ6IPM", Request id "0HL8I8AFQ6IPM:00000001": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Razor.Internal.FileProviderRazorProject.<EnumerateFiles>d__5.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.FileProviderRazorProject.<EnumerateFiles>d__5.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.FileProviderRazorProject.<EnumerateFiles>d__5.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.FileProviderRazorProject.<EnumerateFiles>d__5.MoveNext()
   at Microsoft.AspNetCore.Mvc.RazorPages.Internal.RazorProjectPageRouteModelProvider.OnProvidersExecuting(PageRouteModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionDescriptorProvider.BuildModel()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Internal.ActionDescriptorCollectionProvider.get_ActionDescriptors()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.GetTreeRouter()
   at Microsoft.AspNetCore.Mvc.Internal.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Modules.ModularTenantContainerMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 605.731ms 500

**Comment by sebastienros** [comment]
It works fine for me, tried not later than yesterday. Could you provide detailed repro steps?

**Comment by piskernik** [comment]
It's pretty easy (these are the steps on a Mac but I tried Visual Studio 2017 as well):
```
git clone https://github.com/OrchardCMS/OrchardCore.Samples.git
cd OrchardCore.Samples/ModularApplication
dotnet restore
dotnet build
dotnet publish -o ~/Code/Test/Publish
cd ~/Code/Test/Publish
dotnet ./ModularApplication.dll
```
This application runs then from port 5000: http://localhost:5000/Module1/Home/Index
This shows an empty page (500) in Safari - in Windows 10 with Edge and Visual Studio it was exactly the same (if I publish it from the command line)
If I run it with dotnet run (from ModularApplication directory of course) it runs from a random port without this error.
MiddleWare is working: http://localhost:5000/hello brings the expected result.

**Comment by sebastienros** [comment]
I didn't realize I was on the samples repos .... will try it

**Comment by piskernik** [comment]
Probably solved with https://github.com/OrchardCMS/OrchardCore/pull/1102. Anyhow the sample runs now as expected also as published version.

**Comment by sebastienros** [comment]
That's right, and thanks for posting this is resolved.
